### ISSUE TITLE
async/await keywords not recognized in code block?

### ISSUE THREAD

**Issue by Mariatta** [asottile/blacken-docs#1]
Hi,

My documentation looks like this:

```rst
.. code-block:: python

    async with aiohttp.ClientSession() as session:
        gh = GitHubAPI(session, "mariatta", oauth_token=os.getenv("GH_AUTH"))
```

When I run blacken-docs, I'm getting this error:
```
code block parse error Cannot parse: 1:6: async with aiohttp.ClientSession() as session:
```

But when I removed the `async` keyword, it works:
```rst
.. code-block:: python

    with aiohttp.ClientSession() as session:
        gh = GitHubAPI(session, "mariatta", oauth_token=os.getenv("GH_AUTH"))
```

Same problem when I have this type of code block:
```rst
.. code-block:: python

    await gh.patch(url, data={"state": "closed"})
```
Removing the `await` keyword works.
Any idea?

Thanks.

**Comment by asottile** [comment]
Hello! Thanks for the issue :)

Seems `black` can't parse this either:

```
$ black test.py
error: cannot format /private/tmp/test.py: Cannot parse: 1:6: async with aiohttp.ClientSession() as session:
$ cat test.py
async with aiohttp.ClientSession() as session:
    gh = GitHubAPI(session, "mariatta", oauth_token=os.getenv("GH_AUTH"))
```

Probably because `async with` and `await` are only legal inside an `async def`.

This seems to work for me:

```rst
.. code-block:: python

    async def example():
        async with aiohttp.ClientSession() as session:
            gh = GitHubAPI(session, "mariatta", oauth_token=os.getenv("GH_AUTH"))
```

A bit clunky, but it matches the grammar I guess?

**Comment by Mariatta** [comment]
Thanks :) Now I understand it. But that code will not work for my tutorial documentation.. 
So I guess I just have to avoid adding `.. code-block:: python` there in order for blacken-docs to work at least for other parts of the documentation.

**Comment by asottile** [comment]
One thing I did for `pytest`s documentation was to add a few `...` -- maybe something similar would keep your semantics here?

```rst
.. code-block:: python

    async def example():

        ...

        async with aiohttp.ClientSession() as session:
            gh = GitHubAPI(session, "mariatta", oauth_token=os.getenv("GH_AUTH"))
```

maybe even clunkier, but it might enable the docs to still be parsed 🤷‍♂️

**Comment by asottile** [comment]
Since there's not terribly much that can be done from the `blacken-docs` side I'm going to close this with a sad wontfix.  Thanks again for the issue :)

**Comment by Mariatta** [comment]
Thanks :)
