### ISSUE TITLE
Brakes docstrings when triple single quote (''') is used inside code block

### ISSUE THREAD

**Issue by Higgcz** [asottile/blacken-docs#101]
Not sure whether this is an issue of **blacken**, but I found an interesting example that breaks my code. Basically, I have a function with a docstring that contains an example of a class you can pass to that function as an argument. The important thing is that inside this function I'm extracting the docstring of the class, so I also wanted to include a docstring in that example.

I guess you can see where this is going, here is an example:

```python
def foo(data):
    """Docstring of foo...

    Example:
        ```python
        class Data:
            '''Example docstring of Data'''
            ...
        ```
    """
```

**Blacken** will try to format it and change the inner `'''` to `"""`, which breaks the outer docstring.

When I use `'''` for the outer docstring, **black** won't change it to `"""` because it realizes that would break the string. So I guess that's the cleanest solution for now. Any better ideas?

**Comment by asottile** [comment]
yeah that'll happen, nothing really that can be done about it I'm afraid
