### ISSUE TITLE
using black config file?

### ISSUE THREAD

**Issue by ksdaftari** [asottile/blacken-docs#131]
couldnt tell from documentation but does by default will be blacken-docs use projects black config within `pyproject.toml` example

```
# pyproject.toml
[tool.black]
line-length = 79
```

**Comment by asottile** [comment]
it does not use the configuration file -- here are the supported options: https://github.com/asottile/blacken-docs#usage

**Comment by ksdaftari** [comment]
@asottile understood. yea sorry should have looked at issue board before writing this. seeing your similar coomments in https://github.com/asottile/blacken-docs/issues/62. just wanted to double check. thanks for quick response
