### ISSUE TITLE
Eats rST required blank lines if trailing whitespace present

### ISSUE THREAD

**Issue by auscompgeek** [asottile/blacken-docs#139]
### Input

```rst
.. code-block:: python
    
    foo()
    
and that's it
```

Note the blank lines have trailing whitespace.

### Expected output

```rst
.. code-block:: python

    foo()

and that's it
```

(The trailing whitespace should be removed, and the blank lines should be preserved.)

### Actual output

```rst
.. code-block:: python
    foo()
and that's it
```

(This is invalid reStructuredText.)

**Comment by asottile** [comment]
garbage in, garbage out it seems to me

**Comment by auscompgeek** [comment]
The input is valid rST though.
