### ISSUE TITLE
Take directories as arguments and search for files

### ISSUE THREAD

**Issue by madig** [asottile/blacken-docs#159]
In a CI context, it would be nice to be able to point the tool to folders and have it search for appropriate files itself while ignoring stuff in gitignore. Otherwise, in a CI scripting/tox/command runner context, you'll have to start making different commands for different shells recursively looking for files.

**Comment by asottile** [comment]
search the issue tracker next time

**Comment by madig** [comment]
Oops, sorry. "dir" didn't turn up anything but "directory" did. Would you be interested in a PR raising an error if any filename turns out to be a directory?

**Comment by asottile** [comment]
no need, it already produces an `IsADirectoryError` which is perfectly readable
