### ISSUE TITLE
A `--check` mode would be useful

### ISSUE THREAD

**Issue by simonw** [asottile/blacken-docs#161]
I like to run tests in CI against pull requests that fail if the user forgot to run Black or various other tools.

Black provides a useful `--check` option for this:

    black --check .

It would be great if `blacken-docs` had the equivalent.

**Comment by asottile** [comment]
please search the issue tracker

**Comment by simonw** [comment]
Sorry - didn't see these:

- https://github.com/asottile/blacken-docs/issues/147
- https://github.com/asottile/blacken-docs/issues/91

**Comment by simonw** [comment]
Thanks - I figured out how to solve my problem from those comments. Wrote it up here: https://til.simonwillison.net/sphinx/blacken-docs
