### ISSUE TITLE
Add option or switch default to use the same exit code behaviour as `black`

### ISSUE THREAD

**Issue by RobertCraigie** [asottile/blacken-docs#170]
For my usage of `blacken-docs` I don't care whether or not any files were updated but I do want to be notified if any files could not be reformatted, whether that's due to a syntax error or anything else of that kind. This means that the `--skip-errors` flag doesn't work for my use case unfortunately.

Currently, `blacken-docs` exits with `1` if any files were reformatted *or* if there was an error processing the code block. It would be really helpful if there was an option to exit with `0` even if files were reformatted.

For context, the default `black` behaviour is to exit with `0` when files are reformatted and if there are any errors, it exits with `123`.

Thanks!

**Comment by asottile** [comment]
I have no intention of supporting black's settings or behaviors

**Comment by rattrayalex** [comment]
@asottile to lend a little more color here, we currently have this in our build script:

```sh
# We have to run this command twice in order to be able to catch syntax errors.
# As blacken-docs exits non-zero when either a file has been reformatted or a
# syntax error is encountered then we can't just use the --skip-errors flag
poetry run blacken-docs README.md || poetry run blacken-docs README.md
```

Some kind of `poetry run blacken-docs --exit-0-on-reformatting myfile.md` (bikeshedding reqd) would be useful here, so people don't have to run the script twice just to ensure it didn't throw an invalid syntax error.

**Comment by rattrayalex** [comment]
Additionally, I'll note that this stance:

> I have no intention of supporting black's settings or behaviors

is quite surprising, even after re-reading the README. In particular, this:

> It currently supports the following [black](https://github.com/psf/black) options:

implies to me that any `black` settings which are missing from `blacken-docs` are essentially TODO, not WONTFIX. Would you mind clarifying the README on this subject?
