### ISSUE TITLE
Transform pandoc-style class injection/fenced code blocks

### ISSUE THREAD

**Issue by klieret** [asottile/blacken-docs#177]
Thanks for this really nice package @asottile .

Would you consider accepting added support for snippets of the following form:

```markdown
~~~
def python():
    pass
~~~
{: .language-python}
```

It's being referred to as "fenced code blocks" or "pandoc-style".

It's being recognized by kramdown, for example. You can also check its use [with sourcegraph](https://sourcegraph.com/search?q=context%3Aglobal+%7B%3A+.language-python%7D&patternType=literal).

I have already implemented the corresponding regexp in [my fork](https://github.com/asottile/blacken-docs/compare/main...klieret:blacken-docs:main), so I could add the unit tests, documentation, and open a PR here.

**Comment by asottile** [comment]
seems pretty niche -- there's only 1 repository over 100 stars on github

**Comment by klieret** [comment]
Yeah, we've also now simply started to convert to the other syntax (my solution in the fork was too simplistic)...

So I'm fine with closing this.
