### ISSUE TITLE
blacken-docs crashes with black==19.3b0

### ISSUE THREAD

**Issue by mxr** [asottile/blacken-docs#18]
```console
$ pip freeze | grep black
black==19.3b0
blacken-docs==0.4.0
```

$ cat example.md
![image](https://user-images.githubusercontent.com/252209/54386955-8f8a5580-4670-11e9-8759-16efd24cd568.png)

```console
$ blacken-docs example.md
Traceback (most recent call last):
  File "/Users/mxr/.pyenv/versions/py3.6.5/bin/blacken-docs", line 11, in <module>
    sys.exit(main())
  File "/Users/mxr/.pyenv/versions/3.6.5/envs/py3.6.5/lib/python3.6/site-packages/blacken_docs.py", line 109, in main
    'mode': black.FileMode.AUTO_DETECT,
AttributeError: type object 'FileMode' has no attribute 'AUTO_DETECT'
```

This looks to have changed in https://github.com/ambv/black/pull/618. Per the docs we should just not specify the mode to get auto-detect behavior (see [here](https://github.com/JelleZijlstra/black/blame/6d974809cd878f7cad1f981a1778c92d4f9b0f79/README.md#L76-L79)). I can try to take a stab at this in the next few days.

**Comment by asottile** [comment]
heh I guess that's what you get for "beta" software :'(
