### ISSUE TITLE
Add option to format rST `::` literal code blocks

### ISSUE THREAD

**Issue by auscompgeek** [asottile/blacken-docs#21]
I have a project that uses Sphinx and we have a fair number of literal code blocks in our docs. I would rather not have to ask contributors to not use literal code blocks.

Would you be willing to add an option to format rST literal code blocks (or accept a PR adding such an option)?

**Comment by asottile** [comment]
the problem is `::` does not mean "python code block" and formatting all of those as python would be inappropriate

**Comment by auscompgeek** [comment]
Oh yeah, I understand that bit. But in the scenario where I _know_ that all my literal code blocks are Python code, I would like a close-to-no-friction way to format them.

**Comment by asottile** [comment]
I don't think that's a particularly common case, and won't be the case indefinitely (I assume you want to continue formatting your code as you get new contributions right?  setting an option like that would prevent normal plain-text blocks from being added to your `rst`)

Maybe something like this to wholesale convert?

```bash
sed -i 's/^::$/.. code-block:: python/g' $(git ls-files -- '*.py')
blacken-docs $(git ls-files -- '*.py')
```

for instance with `pytest` I had to comb through and change ~a few code blocks to annotate them as python

**Comment by gyermolenko** [comment]
@asottile 
> the problem is `::` does not mean "python code block" and formatting all of those as python would be inappropriate

If I'm not mistaken, it kinda does mean "python code block".

[rst-literal-blocks](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks)
"Code highlighting can be enabled for these literal blocks on a document-wide basis using the highlight directive and on a **project-wide** basis using the **highlight_language configuration option****. 

[highlight_language](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-highlight_language)
"The default is 'python3'."

So (as I understand it) if there are no conf.py highlight_language variable overwriting defaults - `::` is python3.

**Comment by asottile** [comment]
sphinx is just one of many frontends for rst, assuming sphinx would be incorrect.   Even if we could assume sphinx, we can't know the settings that are configured (`conf.py` is arbitrary code, not a configuration format we can safely or reliably read)

**Comment by gyermolenko** [comment]
totally missed that, thanks for clarification

**Comment by auscompgeek** [comment]
I'll have to mess around with that regex a bit I guess — `::` doesn't have to occur on its own line...

**Comment by tgross35** [comment]
Defaulting wouldn't be rst correct, but would a cli argument like `--code-blocks-python` maybe be workable? Sphinx is pretty common, skipping the language specifier is relatively common for terseness since it defaults.
