### ISSUE TITLE
--diff option

### ISSUE THREAD

**Issue by mattsb42-aws** [asottile/blacken-docs#3]
We have `black` checks in our CI to verify that any PRs/pushes are compliant. It would be nice to be able to include blacken-docs in these checks, but I don't want the CI steps to modify any code. Having a `--diff` option similar to `black` would be a nice feature that would show in our CI what needs to change.

**Comment by asottile** [comment]
Via [`pre-commit`](https://pre-commit.com) you can hook up `pre-commit run --all-files --show-diff-on-failure` (such that every tool doesn't have to independently implement this)

**Comment by mattsb42-aws** [comment]
Yup. The CI check is more there as a sanity check to police ourselves and contributors to make sure we don't have anything slip through.

**Comment by mattsb42-aws** [comment]
Actually, I think I misread that comment. I'll take a look and see if that does what I had in mind.

**Comment by asottile** [comment]
If you're looking for prior art, here's how [`tox-dev/tox` does this](https://github.com/tox-dev/tox/blob/4e7d9091f1f7ffd8042936fe25cd2f66e196f57c/tox.ini#L44)

**Comment by mattsb42-aws** [comment]
Precommit hooks should do what we need. Closing this out.
