### ISSUE TITLE
compatibility with jupyter-sphinx

### ISSUE THREAD

**Issue by basnijholt** [asottile/blacken-docs#35]
I would like to use this on `rst` files that are used in combination with https://github.com/jupyter/jupyter-sphinx.

Here the code blocks are formatted like:
```rst
.. jupyter-execute::
    :hide-code:

    code_here

# or

.. jupyter-execute::

    code_here
```

Specifically, I would like to use it for the Adaptive [documentation](https://adaptive.readthedocs.io/en/latest/tutorial/tutorial.Learner1D.html) ([repo](https://github.com/python-adaptive/adaptive/)).

I've made an attempt myself, but I can't match @asottile's regex wizardry 😉

**Comment by asottile** [comment]
I believe (?) it would be extending this line to also match `jupyter-execute`: https://github.com/asottile/blacken-docs/blob/109732aa39a1cafd631e5015b395fac02eb16ee0/blacken_docs.py#L25

**Comment by basnijholt** [comment]
That is exactly what I tried, but it didn't do the trick.

**Comment by asottile** [comment]
can you show your patch? maybe I can help :)

**Comment by basnijholt** [comment]
https://github.com/basnijholt/blacken-docs/commit/6460931f4eabce5cfe3f83141897fde84e1e0279

Thanks for the help!

**Comment by asottile** [comment]
ah I think you need

```python
    rf'^(?P<indent> *)\.\. (jupyter-execute::|(code|code-block|sourcecode|ipython):: {PY_LANGS})\n' 
```

**Comment by asottile** [comment]
@basnijholt were you going to submit a PR?

**Comment by basnijholt** [comment]
Will you accept it if I make this change?

**Comment by asottile** [comment]
yeah I was hoping you'd send a patch :)

**Comment by basnijholt** [comment]
I've just opened #37! 👍
