### ISSUE TITLE
ignore jupyter magics

### ISSUE THREAD

**Issue by basnijholt** [asottile/blacken-docs#36]
With [`jupytext`](https://github.com/mwouts/jupytext) one can keep notebooks as Markdown files.

Often one uses Jupyter magics (e.g., `%%time`), when running blacken-docs on the `.md` files I get many warnings like:
```
FILENAME_HERE.md:30: code block parse error Cannot parse: 1:0: %load_ext autoreload
```

Would it be possible to easily ignore those magics?

**Comment by asottile** [comment]
`blacken-docs` is just a thin wrapper around `black` -- if black can't parse it I don't think we can either

and even if we did put some weird substitution in place, I'm not sure how it could survive a round of formatting

so I think the answer here is "probably not" -- thanks for the issue though!

**Comment by grst** [comment]
I would also be interested in this. 
Since the cell magics can only occur at the first line of a code chunk, I think it should be rather easy to exclude them. 

In fact, adding a line to your regex parser that skips a line starting with `%` should already solve the problem.

**Comment by MarcoGorelli** [comment]
> In fact, adding a line to your regex parser that skips a line starting with % should already solve the problem.

Unfortunately, this would break:
```python
foo = (
'%s'
% 'bar'
)
```

> if black can't parse it I don't think we can either
> and even if we did put some weird substitution in place, I'm not sure how it could survive a round of formatting

Just FYI, this might soon be happening (https://github.com/psf/black/pull/2357)

In the meantime, there's my little project [nbQA](https://github.com/nbQA-dev/nbQA) which, like the above PR to `black`, transform cells using `IPython`'s `TransformerManager` and `ast.parse` to preserve/round-trip magics
