### ISSUE TITLE
Support Markdown include syntax ({! myfile.py !})

### ISSUE THREAD

**Issue by hjacobs** [asottile/blacken-docs#39]
The "include" syntax should be skipped instead of bailing out:

```
docs/howtos/authenticate-web-ui-users.md:71: code block parse error Cannot parse: 1:1: {! docs/howtos/aiohttp-oauth-redirect-example.py !}
```

Background: we "include" longer Python files (which are separately formatted with black) in Markdown with the [`mdx_include` markdown extension](https://pypi.org/project/mdx-include/).

My proposal would be to detect code blocks which just contain such include syntax (`{! ... !}`) and ignore them.

**Comment by asottile** [comment]
I've never seen `{!  ... !}` -- seems made up / non standard -- can you do this with a comment (valid python syntax) instead?

**Comment by hjacobs** [comment]
@asottile the Markdown include is an extension, but there are multiple extensions using the same markup (https://pypi.org/project/mdx-include/, https://github.com/cmacmackin/markdown-include), so it's a de-facto-standard for includes in `.md` files I would say. This "include" rule is not Python-specific and I don't want to invent another Markdown extension for this specific use case.

A Python comment (`# {! ... !}`) won't work as this would comment out the first line of the included file (of course I can make the first line in the file a comment also, but then I see a "double comment" in the code block).

**Comment by asottile** [comment]
you could start your included file with a newline

but in reality you don't need blacken-docs if you can include python files *and* it's not markdown you're using so I'm closing this - run black on your included files should continue to work fine for you

**Comment by hjacobs** [comment]
@asottile sorry, but you did not understand my point: the included files ARE black-formatted, but I ALSO want formatting for the (smaller) code blocks.

**Comment by asottile** [comment]
yes I am suggesting one or the other and not both
