### ISSUE TITLE
pass --check option to black

### ISSUE THREAD

**Issue by shamrin** [asottile/blacken-docs#42]
`black` supports `--check` option, useful for CI:

```
--check                           Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted.  Return code 123 means
                                  there was an internal error.
```

I've read the discussion in #3. It is helpful, but I believe there should be a way to use blacken-docs in CI without depending on `pre-commit` tool.

Are you open to this feature?

**Comment by asottile** [comment]
no, sorry -- for the same reasons as #3

it's not simply passing through the option as we don't even access the part of black that does checking -- it would be implementing it and supporting it here which I am not interested in doing

thanks for the issue anyway!

**Comment by shamrin** [comment]
Could you please reconsider? Unfortunately, we can't depend on `pre-commit` tool.

You are right that it's not enough to pass `--check` to black. However, the implementation was almost trivial. (I've implemented it before seeing your message.)

https://github.com/asottile/blacken-docs/pull/43

**Comment by asottile** [comment]
no, I don't want to support that feature

**Comment by asottile** [comment]
note that you can already use the exit code (this tool returns nonzero when making changes)

**Comment by shamrin** [comment]
Ok, no problem!

Thank you for info about exit code note. Unfortunately, I don't want `blacken-docs` to change files under me.

By the way, I've found a work-around for non-destructive format checking:

```console
./markdowncode README.md | black --check --diff -
```

`markdowncode` is a small script that extracts all Python code blocks:

```python
#!/usr/bin/env python3
"""Extract Python code blocks from markdown file"""

import re
import sys
from textwrap import indent

doc = open(sys.argv[1])
m = re.search(r"```python(.*)```", doc.read(), re.DOTALL)
if m:
    for i, group in enumerate(m.groups()):
        print(f'def test_{i}():\n{indent(group, " " * 4)}', end="")
```

**Comment by asottile** [comment]
cool, thanks for sharing

**Comment by shamrin** [comment]
I've developed [my example above](https://github.com/asottile/blacken-docs/issues/42#issuecomment-583371016) further and published it as [`codeblocks` command](https://github.com/shamrin/codeblocks/). It supports `black --check` directly:

```
codeblocks python README.md | black --check -
```

In addition, it has its own `--check` param, to compare `black` output with Markdown code block content:

```
codeblocks --check python README.md -- black -
```

`codeblocks` can also do linting, type checking and keeping `--help` up-to-date.

**Comment by asottile** [comment]
@shamrin not a place for advertising
