### ISSUE TITLE
Eliminate trailing whitespace

### ISSUE THREAD

**Issue by epogrebnyak** [asottile/blacken-docs#56]
Does (should?) blacken-docs eleimnated trailing whitespace in .md files? 

I did run `blacken-docs index.md` on a file with some trailing space with no effect.

**Comment by asottile** [comment]
can you share your example file (probably need to attach it to preserve the whitespace).  black will remove trailing whitespace in the python code blocks (and that's the point of the tool)

if you're talking about outside of code blocks then no, that's outside the scope.  you probably want [`trailing-whitespace`](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) to handle that

note that removing trailing whitespace from markdown is *actually controversial*, so check out the related issues in that project as well

**Comment by epogrebnyak** [comment]
My example concerns trailing whitespace in `index.md` file and not python code block. 

I was acting under inpression of tagline in README.md, maybe it is a good idea to modify it:

> blacken-docs provides a single executable (blacken-docs) which will modify .rst / .md / .tex files in place.

I'm closing the issue as my orignial question is out of scope of the tool. 

I still need something that I can brush up markdown files quickly with, but maybe I need some of VS code extensions. 

https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace looks good functionality, but I do not understand prehooks and will be looking something usable stand-alone.

Thanks for you comments and suggestions.

**Comment by asottile** [comment]
it is usable standalone: https://github.com/pre-commit/pre-commit-hooks#as-a-standalone-package
