### ISSUE TITLE
IO instability ?

### ISSUE THREAD

**Issue by neutrinoceros** [asottile/blacken-docs#72]
I think blacken-docs choked on its own outputs here
https://results.pre-commit.ci/run/github/88776493/1611352950.Q5AmQc6QSAKgtcvX2OMkpg

It ran successfully the first time but apparently couldn't parse back what it wrote on the checking run.
This is not a big deal for me, I just wanted to let you know :)

edit: here's the PR link https://github.com/yt-project/yt/pull/3032

**Comment by asottile** [comment]
I started looking through these and the "Cannot parse" bit looks correct.  There are existing syntax errors in your code samples.  black or blacken-docs can't magically fix those

**Comment by neutrinoceros** [comment]
well that was fun ! Thanks for taking a look a it so promptly !
