### ISSUE TITLE
Support pycon language in markdown.

### ISSUE THREAD

**Issue by proofit404** [asottile/blacken-docs#74]
It useful to write doctest inside markdown files.

```markdown
    ```pycon

    >>> def foo ( bar,) : 
    ...     return ''

    ```
```

I saw it is supported for restructured text.

Maybe there is a relatively easy way to do the same for markdown?

**Comment by asottile** [comment]
yeah should be relatively straightforward to apply the same logic -- CC @jdufresne

**Comment by proofit404** [comment]
Hello, 

Sorry for being late to the discussion.

Is there anything left to do? Or the issue was completely implemented in related pull request?

thx @Spectre5
