### ISSUE TITLE
Support sphinx.ext.doctest directives

### ISSUE THREAD

**Issue by Spectre5** [asottile/blacken-docs#78]
I have a project where most of the reStructuredText python source is in a `.. testcode:: python` block instead of `.. code-block:: python`.  Can support be added for the `testcode` block, and potentially the `doctest` one too?

https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html

**Comment by asottile** [comment]
there's already [a bunch of others](https://github.com/asottile/blacken-docs/blob/67dd1372cc3db5c2f15399c70bf344d0d02ac320/blacken_docs.py#L23) if you're looking for a place to augment

patches welcome!
