### ISSUE TITLE
Parse error for >>> prompt in code examples

### ISSUE THREAD

**Issue by cdeil** [asottile/blacken-docs#8]
Sphinx supports docs code examples with a prompt and output, as in the example from http://www.sphinx-doc.org/en/stable/markup/code.html
```
>>> 1 + 1
2
```

Such code blocks are present in most docs files in the projects I work on, and `blacken-docs` gives a "code block parse error" for those and I think skips them completely, so doesn't work for me (and I think many other people / projects) at the moment.

There must be some code in `sphinx` to parse those out, and to syntax highlight the rest of the code, so it should be possible to import and use that part of sphinx and only process the code after stripping the `>>>` out.

**Comment by asottile** [comment]
there's a separate "python console" and "python" highlighting for sphinx

blacken-docs currently only supports `.. code-block python` and `python` markdown blocks

If you can make the parsing work I'd take a PR, it shouldn't be terribly difficult to parse out statements, it gets tricky when you have line continuations though

(note I'm using the `pycon` markdown language here)

```pycon
>>> print(
...     'hello'
...     'world'
... )
helloworld
```

**Comment by cdeil** [comment]
Probably won't have time to look into the Sphinx parsing and send a PR.

Is changing `blacken-docs` to process one code block at a time, and to continue with later code blocks if one causes a parse error possible / a good idea?

I think at the moment a file is skipped completely if a parse error occurs, right?

**Comment by cdeil** [comment]
Another issue I found is that in the projects I work on (Python projects using Sphinx) many code examples start with `::` instead of `code-block:: python`, and Sphinx will automatically process those as code blocks.

`blacken-docs` doesn't seem to recognise those code blocks, i.e. doesn't even try to process most code blocks.

So I guess now that I understand a bit better what blacken-docs does (use just regexes), my  feature request here is more: please support Python sphinx docs better, by behaving more like Sphinx.

**Comment by asottile** [comment]
`::` in sphinx is just "format a code block for me please".  blacken-docs intentionally only will format things that are explicitly marked as `python` code blocks.

Also note that `sphinx`'s behaviour (while the most popular `.rst` formatter) is not always standard rst behaviour.

**Comment by asottile** [comment]
> I think at the moment a file is skipped completely if a parse error occurs, right?

this is correct -- I could go either way on this, the current implementation keeps this simple and avoids parsing problems for malformed things by bailing whenever it sees something unexpected -- with the idea that you incrementally fix the code blocks so they _can_ be parsed

**Comment by asottile** [comment]
> > with the idea that you incrementally fix the code blocks so they can be parsed
>
> Easier said than done.

:man_shrugging: it wasn't that hard for [pytest-dev/pytest](https://github.com/pytest-dev/pytest/pull/3528/commits/5c878001eaaf55859c0ae0f0d32b067415592b87) or [tox-dev/tox](https://github.com/tox-dev/tox/pull/835/files) (didn't split it into another commit, but it need a single `,` to fix the parsing)

and again, I'd be happy to have a PR to support more forms of things.  As it is right now it's a dead simple wrapper around `black` with some extremely timid pattern matching.

At the very least if `.. plot ::` is unambiguously python code, that seems like an easy enhancement :)

**Comment by asottile** [comment]
Note that there's a new `--skip-errors` option (contributed by @PhilipTrauner in https://github.com/asottile/blacken-docs/pull/11) which should help for one of the issues here (continue on failure).

**Comment by dougthor42** [comment]
> there's a separate "python console" and "python" highlighting for sphinx

Just so I'm clear, you're referring to the special [doctest-blocks](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#doctest-blocks) case, correct? Eg:

```rest
This is an ordinary paragraph.

>>> print('this is a Doctest block')
this is a Doctest block
>>> 1+ 1
2

and this is not part of the doctest block
```

Or are you referring to some pygments lexer that I'm not aware of?

**Comment by asottile** [comment]
I'm referring to the separate pygments lexer https://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer

**Comment by dougthor42** [comment]
Ah, thanks! I learned something new today :-)
