### ISSUE TITLE
support asciidoc

### ISSUE THREAD

**Issue by rochacbruno** [asottile/blacken-docs#81]
I am writing a lot of asciidoc and this tool would give me some help, is your interest to support asciidoc?

```adoc
[source,python]
def foo():
   return "bar"
```

https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/

**Comment by asottile** [comment]
sure, send a patch!

**Comment by rochacbruno** [comment]
@asottile nice! I gonna try to prepare a PR :)

**Comment by eirnym** [comment]
@rochacbruno any success?

**Comment by eirnym** [comment]
@asottile why issue has been closed before PR has been sent? Could you please reopen it till support has been added?

**Comment by adamchainz** [comment]
I would be happy to reopen if there were a well tested patch, but I’m not planning on adding support myself, so there’s no point having ab open issue.
