### ISSUE TITLE
VS Code extension?

### ISSUE THREAD

**Issue by arnaudmiribel** [asottile/blacken-docs#92]
Thanks a lot for this project! 

Is there any VS Code extension existing for that already? Otherwise, happy to dig into doing one!

**Comment by asottile** [comment]
not that I know of!

**Comment by arnaudmiribel** [comment]
If anyone's interested: easiest was in fact to append a shortcut within `Preferences: Open Keyboard Shortcuts (JSON)`. 
See [this SO message](https://stackoverflow.com/a/52786528/6159698) for more context.

So now whenever <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>B</kbd>, I `blacken-doc` the active file.

```json
{
        "key": "ctrl+shift+b",
        "command": "workbench.action.terminal.sendSequence",
        "args": {
            "text": "blacken-docs '${file}'\u000D"
        }
    }
```
